spring.application.name=mensageria
spring.profiles.active=console
#spring.profiles.active=twilio
# envia pelo WhatsApp (S� funciona com o n�mero do Gabriel)

# ===== Server Port =====
server.port=8081

# ===== RabbitMQ =====  (coloca o ip do rabbit que mostra ap�s o terraform apply)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=30000
spring.rabbitmq.requested-heartbeat=60
spring.rabbitmq.channel-close-timeout=30000
spring.rabbitmq.network-recovery-interval=5000
spring.rabbitmq.automatic-recovery-enabled=true

app.rabbitmq.exchange.consultas-criadas=consultas.criadas.exchange
app.rabbitmq.queue.consultas-criadas=consultas.criadas.queue
app.rabbitmq.routing-key.consultas-criadas=consultas.criadas

# Flag opcional para ligar/desligar listeners
app.rabbitmq.enabled=true

# ===== Twilio =====
twilio.account-sid=
twilio.auth-token=
twilio.whatsapp.from=

